[[Cliquer]]
arch = "aarch64"
git-tree-sha1 = "8e6a107f011d0908e9e47198cecae133c57e9aee"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "db6c04d044143b48d62824d63a01b6dfd681f1a858e2873f2c7136e6ad03a4f7"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.6+0/Cliquer.v1.21.6.aarch64-linux-gnu.tar.gz"
[[Cliquer]]
arch = "aarch64"
git-tree-sha1 = "3cf4030585fffd29fcdcdfd84a95a23fa3cd674f"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "e09d9dbd62e6cc940907587e6716204e90275d618f10e8cf2084e8d235a58d1f"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.6+0/Cliquer.v1.21.6.aarch64-linux-musl.tar.gz"
[[Cliquer]]
arch = "armv7l"
git-tree-sha1 = "32b0fed8f68f9d43ee9a5284cf4396fc6d799f21"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "5bc784036309e857f12cbe646fed0648f37954860ebf11490f8962a44756c7ae"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.6+0/Cliquer.v1.21.6.armv7l-linux-gnueabihf.tar.gz"
[[Cliquer]]
arch = "armv7l"
git-tree-sha1 = "f53acede66fc2adcd3c4bfef55d4d323240d344d"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "84a4e61e2f1b964acfab41283626a464d2d22372edd86ed4046e61345ca3a11a"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.6+0/Cliquer.v1.21.6.armv7l-linux-musleabihf.tar.gz"
[[Cliquer]]
arch = "i686"
git-tree-sha1 = "bc15925e5965d2d3a8b2a04f13e57111e3e4df02"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "12b81f223bdb5c140281f47f2d81c1e1d82c231751ad65e79bc1415ff176c4e6"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.6+0/Cliquer.v1.21.6.i686-linux-gnu.tar.gz"
[[Cliquer]]
arch = "i686"
git-tree-sha1 = "85a0e8e6f21aaaa71323beacba48aba0daca2c3c"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "4e194fe3e82b9c05a773b4a7b7b84c89f6921e9e08f569e8d26b8aabc8a3a0fe"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.6+0/Cliquer.v1.21.6.i686-linux-musl.tar.gz"
[[Cliquer]]
arch = "powerpc64le"
git-tree-sha1 = "e9612b3b9f882784e705a8dce73d60556c6d6962"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "1e7104d2dfceeac19db7d1e8d674676c197e248b92f6cb6d45a9d41f360a8a41"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.6+0/Cliquer.v1.21.6.powerpc64le-linux-gnu.tar.gz"
[[Cliquer]]
arch = "x86_64"
git-tree-sha1 = "605f5a7ab5456905ac54662906cff4d9f246b74b"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "ae542d884719723a6836fbc1c149c233922467f97d7ca9bb0d9ff26dbcb60b42"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.6+0/Cliquer.v1.21.6.x86_64-linux-gnu.tar.gz"
[[Cliquer]]
arch = "x86_64"
git-tree-sha1 = "dddc8088f89a9b94545359e2c1dd94eb52d5d4ed"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "a121824627d6aa016855b177deddaf5bec02e90becf14d298b59560d78da56b9"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.6+0/Cliquer.v1.21.6.x86_64-linux-musl.tar.gz"
