[[Cliquer]]
arch = "aarch64"
git-tree-sha1 = "62816595436c137bd23d079245dc6355eb52250f"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "8edf96880f4f8e004cd757941388205fc45fd857cf9e252de2f4a8acde99fec2"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.5+0/Cliquer.v1.21.5.aarch64-linux-gnu.tar.gz"
[[Cliquer]]
arch = "aarch64"
git-tree-sha1 = "49d3b58fea419b9528736cba969ae368e1548a1a"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "8e6d43a7b387d16dd0c684a4ab370ef24dffdb71e496285dd676ebd3b771ccc0"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.5+0/Cliquer.v1.21.5.aarch64-linux-musl.tar.gz"
[[Cliquer]]
arch = "armv7l"
git-tree-sha1 = "4e270f61c6fb74e0dda9456a3f44d86c94298bc4"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "102584ac1eb81d7681be5d7065c3717da544d5f9ebd09b650b351015ba705e8a"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.5+0/Cliquer.v1.21.5.armv7l-linux-gnueabihf.tar.gz"
[[Cliquer]]
arch = "armv7l"
git-tree-sha1 = "32f43dcd1e6b30906f66248af1c32c754fbd0136"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "04d9ec5d3886d991e470ce17c6045aef70ae16f2a608e3c8057abd6cfe3ae1b0"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.5+0/Cliquer.v1.21.5.armv7l-linux-musleabihf.tar.gz"
[[Cliquer]]
arch = "i686"
git-tree-sha1 = "616c8428a7be047066925efa5d13c71728709a27"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "71311318e863bebf2a00ccbc9b4346c23471145194c46fe733ddee1026877290"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.5+0/Cliquer.v1.21.5.i686-linux-gnu.tar.gz"
[[Cliquer]]
arch = "i686"
git-tree-sha1 = "bb6e413baf0cf8cdea7365df2eab7f4b3076480b"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "ca3bd6892e8f2979bfd39340d0952e3a55b00f6ba520041c5d6c5ac9be0d9f33"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.5+0/Cliquer.v1.21.5.i686-linux-musl.tar.gz"
[[Cliquer]]
arch = "powerpc64le"
git-tree-sha1 = "f8a437bb90c6b6f86d0efd22056dce66b1e0f7b8"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "ff962b7215e1c1c32587a1e25b2f5839c446c8d13549de986267c7c21d7061d4"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.5+0/Cliquer.v1.21.5.powerpc64le-linux-gnu.tar.gz"
[[Cliquer]]
arch = "x86_64"
git-tree-sha1 = "f5d50f6f84d2923532afafcb8a0cad0dc9eac2a3"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "e7d3cbe5a94f0485fb8e07f6d9fa06d4d4b7255f99d1b1d04221ebf7dcfe0d19"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.5+0/Cliquer.v1.21.5.x86_64-linux-gnu.tar.gz"
[[Cliquer]]
arch = "x86_64"
git-tree-sha1 = "e0879986eb4bd8757c183ba008dbe83911540f06"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "3bbd7d62b7afb1e04cda32c23a47b763b9bee27bc6b9aa578358066cdb4aff25"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.5+0/Cliquer.v1.21.5.x86_64-linux-musl.tar.gz"
