[[Cliquer]]
arch = "aarch64"
git-tree-sha1 = "82e3e97aca4f76f9e8753cbe60994a53420dca49"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "5124e0ae56713bdf31176323bf804cad000b12fdbcd9fbf20b0d9aeeb42a3259"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.1+0/Cliquer.v1.21.1.aarch64-linux-gnu.tar.gz"
[[Cliquer]]
arch = "aarch64"
git-tree-sha1 = "a8b03a1828428f93debb11e013a34850d78a23b3"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "368f82d6237f77a34e8af82937b392900d6d174c9f5f006546b7fd1a0113be6c"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.1+0/Cliquer.v1.21.1.aarch64-linux-musl.tar.gz"
[[Cliquer]]
arch = "armv7l"
git-tree-sha1 = "a7dbf49d926c493f6c9e74df23d28b709034c856"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "fe5aa7acf2255d11d083e6d4d33aeb284d2196317c38717763f849a1f59f2f77"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.1+0/Cliquer.v1.21.1.armv7l-linux-gnueabihf.tar.gz"
[[Cliquer]]
arch = "armv7l"
git-tree-sha1 = "d58fc264f9f0dd7368b2c5870ae64edb211deaf2"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "056740db13711b7dab805dcb10982659c77fbe65eeea92f68e1b0325da46032b"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.1+0/Cliquer.v1.21.1.armv7l-linux-musleabihf.tar.gz"
[[Cliquer]]
arch = "i686"
git-tree-sha1 = "3eea7fe671ffae19cccda6181f24a711dd10b25f"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "629e0f1067c75703cd60cb4d75ccaa073ed66888f1aa05e41e5b8403cf9a2b2f"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.1+0/Cliquer.v1.21.1.i686-linux-gnu.tar.gz"
[[Cliquer]]
arch = "i686"
git-tree-sha1 = "6f48884f3ee7be88c1a3b687186ba7e53521af75"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "55d7aeb48ce0fc13f0d479fe718f86dc8ed26e6abcd4cadf02a8d229b5c33caa"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.1+0/Cliquer.v1.21.1.i686-linux-musl.tar.gz"
[[Cliquer]]
arch = "powerpc64le"
git-tree-sha1 = "65119d451d940ae5de44b8c56a8f26699d823ec8"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "aa36374eb5d565bdeb2608358e64d9b33ea6491f35e32f12181eb0ce32fe91eb"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.1+0/Cliquer.v1.21.1.powerpc64le-linux-gnu.tar.gz"
[[Cliquer]]
arch = "x86_64"
git-tree-sha1 = "f9826f15fcef070689084371d03a6c152b156abf"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "77a733e3d865b196dfab86089925d55ab742b54b1e3afdee32643300a1cac78d"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.1+0/Cliquer.v1.21.1.x86_64-linux-gnu.tar.gz"
[[Cliquer]]
arch = "x86_64"
git-tree-sha1 = "07f56b25e9604fdffb411717fdbe163c484719cd"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "e240969b69461d745ab41f328e73c2ff6ae55d7ed5aa1a3f0e4ebb08637ec125"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.1+0/Cliquer.v1.21.1.x86_64-linux-musl.tar.gz"
