[[Cliquer]]
arch = "aarch64"
git-tree-sha1 = "bb6d1d02132be4169aed702d8eeae6b6fa095978"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "866664b1fc19de7c16990a2a289092e02156d87aae726a17bc4e0a26b1471110"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.0+0/Cliquer.v1.21.0.aarch64-linux-gnu.tar.gz"
[[Cliquer]]
arch = "aarch64"
git-tree-sha1 = "2be0efbee32973b23585b1dd3da2fc2377d88125"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "9eb7305aef86605f413a6a9feb62823328eb07111eb8fcb932bb93190878790d"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.0+0/Cliquer.v1.21.0.aarch64-linux-musl.tar.gz"
[[Cliquer]]
arch = "armv7l"
git-tree-sha1 = "7deb75dc1d5505cdb73179114125cd509015db9a"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "41f6f4c5292c87e64977d159d582af44993ae2a172b675b01c5a3b91a9aad4f3"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.0+0/Cliquer.v1.21.0.armv7l-linux-gnueabihf.tar.gz"
[[Cliquer]]
arch = "armv7l"
git-tree-sha1 = "e0eaea2cc385efb2a6bd4ee7623791bf2673fc39"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "f256c973c49965b909b8fca95ae02b7ee7b3d310547e9674de29a7f61b96625f"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.0+0/Cliquer.v1.21.0.armv7l-linux-musleabihf.tar.gz"
[[Cliquer]]
arch = "i686"
git-tree-sha1 = "94b4bbf29523981db1aa775f84568ddba67ecd98"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "956e9ea72ea60c988c130760ab554b17425199f0d08a915bb0b8036dcfedaa42"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.0+0/Cliquer.v1.21.0.i686-linux-gnu.tar.gz"
[[Cliquer]]
arch = "i686"
git-tree-sha1 = "fb59e3c56bfdf25fe3a54f0ef30e5fc7a8e83dff"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "a2a1b0dc323902619058c308f61a29f49042fbcb22ba0eb34cb8035ca769fee5"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.0+0/Cliquer.v1.21.0.i686-linux-musl.tar.gz"
[[Cliquer]]
arch = "powerpc64le"
git-tree-sha1 = "c19dd4bb83ab8b6b01b78edea67888e2e73aec20"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "db8b8767516d59e57c89cbfce4c18b2d0bdc33c223118aa62791e309d9b77b59"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.0+0/Cliquer.v1.21.0.powerpc64le-linux-gnu.tar.gz"
[[Cliquer]]
arch = "x86_64"
git-tree-sha1 = "2a9fda306213c5d1ef2cb4651b1808bd90b9dc89"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "54a81846331888dd29ad23adae39cd8227a18a6939b89498c7258b7afa6fb349"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.0+0/Cliquer.v1.21.0.x86_64-linux-gnu.tar.gz"
[[Cliquer]]
arch = "x86_64"
git-tree-sha1 = "5cb670e41e81b725ca7e7c09dbfaa85d4d585f44"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "f32808188adc62ba67782185c8ec01821342eacba9c46c7e04f5d87b5e9b9b55"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.0+0/Cliquer.v1.21.0.x86_64-linux-musl.tar.gz"
