[[Cliquer]]
arch = "aarch64"
git-tree-sha1 = "3859c6984747894b63fe3bcbbc50b91f44c71536"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "7d8a850275dc95e59a7bb42aa5877f3f2ea7d5ef3e52960964dccdc772636174"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.3+0/Cliquer.v1.21.3.aarch64-linux-gnu.tar.gz"
[[Cliquer]]
arch = "aarch64"
git-tree-sha1 = "232225f18fe993a66f3e923520bacdd22b661ded"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "c3b1b8e5debe10e0bb2cdd5be576885a1361c266f477193fc6b11b3698a24304"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.3+0/Cliquer.v1.21.3.aarch64-linux-musl.tar.gz"
[[Cliquer]]
arch = "armv7l"
git-tree-sha1 = "daf2a081209f69c1d00356bca51fc5b16644e745"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "ea16cc7cb57156312ec5d3aa397804d4a65a063170a780d22899155ae32af589"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.3+0/Cliquer.v1.21.3.armv7l-linux-gnueabihf.tar.gz"
[[Cliquer]]
arch = "armv7l"
git-tree-sha1 = "4172389d4b84424e31b31c9b7d199972eb385201"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "a3162574a2d076b6ab730708cc883c6e4c5dbb4e223a03bf8672b915b1fcd3b7"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.3+0/Cliquer.v1.21.3.armv7l-linux-musleabihf.tar.gz"
[[Cliquer]]
arch = "i686"
git-tree-sha1 = "1bde8b8bde0443663fec0ccca4fd1346e9bf1f29"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "4b560e4d88454dd6b3e07bbf335ef88bff2e69059f7aa34d66f9205d82b5a05f"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.3+0/Cliquer.v1.21.3.i686-linux-gnu.tar.gz"
[[Cliquer]]
arch = "i686"
git-tree-sha1 = "e3c80f112e471d909357e0ba0381240fe13e78cf"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "bcd508bf82fba6875e13759d6fd48aa9e2067a0f008c2d2c7432adffc43a4bf6"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.3+0/Cliquer.v1.21.3.i686-linux-musl.tar.gz"
[[Cliquer]]
arch = "powerpc64le"
git-tree-sha1 = "ada93a2213d90a684eb716cc95c6fb611cd899ae"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "54ef9e34aec4b470833ebb6dbf206e83852c309c2e9400757533203266075444"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.3+0/Cliquer.v1.21.3.powerpc64le-linux-gnu.tar.gz"
[[Cliquer]]
arch = "x86_64"
git-tree-sha1 = "d2e09fd7cb866cf80a584f6a9c06abf79364d418"
libc = "glibc"
os = "linux"

    [[Cliquer.download]]
    sha256 = "3c8830cb6044504ff9b8f9e75faa2eb067742d8d87125174a2de141dd8101056"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.3+0/Cliquer.v1.21.3.x86_64-linux-gnu.tar.gz"
[[Cliquer]]
arch = "x86_64"
git-tree-sha1 = "06e6a8d9d968e5db3857eefe3eb415ed624eace3"
libc = "musl"
os = "linux"

    [[Cliquer.download]]
    sha256 = "b1c4ad83250c5861699e6aa690fcfc2730fbc7558f5f135fc9faea04685e18b6"
    url = "https://github.com/claud10cv/Cliquer_jll.jl/releases/download/Cliquer-v1.21.3+0/Cliquer.v1.21.3.x86_64-linux-musl.tar.gz"
